# Generated by Django 2.2.7 on 2019-11-19 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20191119_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='short_name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
